"""add_cascading_deletes_for_user_relations

Revision ID: 1c66adb3e247
Revises: 79ab17cf8352
Create Date: 2025-09-18 11:48:19.861395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c66adb3e247'
down_revision = '79ab17cf8352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('applications_user_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('audit_logs_actor_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('beneficiaries_application_id_fkey', 'beneficiaries', type_='foreignkey')
    op.create_foreign_key(None, 'beneficiaries', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('documents_application_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('next_of_kin_application_id_fkey', 'next_of_kin', type_='foreignkey')
    op.create_foreign_key(None, 'next_of_kin', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payments_application_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('spouses_application_id_fkey', 'spouses', type_='foreignkey')
    op.create_foreign_key(None, 'spouses', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spouses', type_='foreignkey')
    op.create_foreign_key('spouses_application_id_fkey', 'spouses', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_application_id_fkey', 'payments', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'next_of_kin', type_='foreignkey')
    op.create_foreign_key('next_of_kin_application_id_fkey', 'next_of_kin', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_application_id_fkey', 'documents', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'beneficiaries', type_='foreignkey')
    op.create_foreign_key('beneficiaries_application_id_fkey', 'beneficiaries', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_actor_user_id_fkey', 'audit_logs', 'users', ['actor_user_id'], ['id'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_user_id_fkey', 'applications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
